language: objective-c
before_install:
    - gem install cocoapods
    - brew update
    - brew unlink xctool
    - brew install xctool
script: xctool -workspace iOS_SoftwareProductLine.xcworkspace -scheme iOS_SoftwareProductLineTests test